### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by aidangadberry** [aidangadberry/facenovel#2]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components and Containers
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by andywynkoop** [comment]
Hey Aidan, 
Here are a few changes I'd like you to make for the user auth mvp:
- [x] Add Logout button (if you want to put it in a dropdown menu later that's fine, but you should have something temporary to allow the user to log out)
- [x] Fonts and icons give a 404 error in the console (asset path problem?)
- [x] Remove redux logger in production
- [x] Remove all console logs
- [x] Errors should display somewhere when failing to log in
- [x] Errors should not move other elements on the page
- [x] If I try to click the sign up button multiple times, the error messages stack on top of each other
- [x] There should be some validations on password for sign up
- [x] When I log in, I get a 'cannot read property then of undefined error
- [x] Log in button should have `cursor: pointer` on hover
